fn main =>
    int a = 4
    if a =|= 0 : 1 : 2 : 3 doremi 0
    if a =<= 0 : 1 : 2 : 3 doremi 0
    if a =>= 0 : 1 : 2 : 3 doremi 0
    if a =!= 0 : 1 : 2 : 3 doremi 0
    if a =&= 0 : 1 : 2 : 3 doremi 0

    elif a =|= 0 : 1 : 2 : 3 doremi 0
    elif a =<= 0 : 1 : 2 : 3 doremi 0
    elif a =>= 0 : 1 : 2 : 3 doremi 0
    elif a =!= 0 : 1 : 2 : 3 doremi 0
    elif a =&= 0 : 1 : 2 : 3 doremi 0

    while a =|= 0 : 1 : 2 : 3 doremi 0
    while a =<= 0 : 1 : 2 : 3 doremi 0
    while a =>= 0 : 1 : 2 : 3 doremi 0
    while a =!= 0 : 1 : 2 : 3 doremi 0
    while a =&= 0 : 1 : 2 : 3 doremi 0
;