#define VAR_ERR_COM "[Variable]: Variable declaration already complete: "
#define VAR_ERR_ERR "[Variable]: Unexpected error"
#define VAR_ERR_INC "[Variable]: Variable declaration incomplete: "
#define VAR_ERR_INV "[Variable]: Invalid Declaration"
#define VAR_ERR_NON "[Variable]: No token available"
#define VAR_ERR_POI "[Variable]: Pointer infront of type not allowed: "
#define VAR_ERR_SET "[Variable]: Invalid value setter"
#define VAR_ERR_TEM "[Variable]: Variable declaration cannot have template without id and type: "
#define VAR_ERR_TYP "[Variable]: Expected return value type got: "
#define VAR_ERR_VAL "[Variable]: Invalid value"