#define ARG_END ") {\n"
#define ARG_SEP ", "
#define ASSIGNMENT " = "
#define BLOCK_END "}\n"
#define BLOCK_START " {\n"
#define CHAR_QUOTE '"'
#define CHAR_SINGLE '\''
#define CLASS "class "
#define COMPILER_OUT " -o "
#define CPP_SUFFIX ".cpp"
#define EMPTY ""
#define ENUM "enum "
#define ENUM_SEP ",\n"
#define FOR_AFTER_UNTIL "; "
#define FOR_END "++) {\n"
#define FOR_MID " = 0; "
#define FOR_START "for(int "
#define FOR_UNTIL " < "
#define HA_SUFFIX ".ha"
#define INCLUDE "#include "
#define INHERIT ": public "
#define LARROW "<"
#define LINE_END ";\n"
#define LPAREN "("
#define NAMESPACE "using namespace "
#define NEWLINE "\n"
#define PRIVATE_STATE " private:\n"
#define PROTECTED_STATE " protected:\n"
#define PUBLIC_STATE " public:\n"
#define QUOTE "\""
#define RARROW ">"
#define RBRACK "}"
#define RETURN_VALUE_IDS "return_value"
#define RPAREN ")"
#define SPACE " "
#define STRUCT "struct "
#define TAB "   "
#define TEMPLATE "template <typename "
#define TEMPLATE_END ">\n"
#define TEMPLATE_MID ", typename "
#define VOID "void"