#[derive(Debug, Copy, Clone, PartialEq)]
pub enum Token {
    Asterix,
    Class,
    Comma,
    Comment,
    Condition,
    CoolArrow,
    DblLessThan,
    DblMoreThan,
    Do,
    Dobr,
    Doco,
    Dore,
    Doremi,
    EOF,
    Equality,
    Equals,
    Extend,
    For,
    ForwardSlash,
    Function,
    Get,
    Global,
    Id,
    Include,
    LBrack,
    LessThan,
    Let,
    LParen,
    MacroDefinition,
    MoreThan,
    NewLine,
    Number,
    Private,
    Protected,
    Public,
    RBrack,
    Return,
    RParen,
    SemiColon,
    Struct,
    Sub,
    Until,
    Sum,
    Type,
    Use,
    False,
    True,
    Compiler,
}

impl Token {
    pub fn from(s: String) -> Token {
        match s.as_str() {
            "-" => Token::Sub,
            "," => Token::Comma,
            ";" => Token::SemiColon,
            "(" => Token::LParen,
            ")" => Token::RParen,
            "[" => Token::LBrack,
            "]" => Token::RBrack,
            "*" => Token::Asterix,
            "/" => Token::ForwardSlash,
            "//" => Token::Comment,
            "\n" => Token::NewLine,
            "+" => Token::Sum,
            "<" => Token::LessThan,
            "<<" => Token::DblLessThan,
            ">>" => Token::DblMoreThan,
            "=" => Token::Equals,
            "==" => Token::Equality,
            "=>" => Token::CoolArrow,
            "compiler" => Token::Compiler,
            ">" => Token::MoreThan,
            "0" => Token::Number,
            "1" => Token::Number,
            "2" => Token::Number,
            "3" => Token::Number,
            "4" => Token::Number,
            "5" => Token::Number,
            "6" => Token::Number,
            "7" => Token::Number,
            "8" => Token::Number,
            "9" => Token::Number,
            "char" => Token::Type,
            "class" => Token::Class,
            "def" => Token::MacroDefinition,
            "do" => Token::Do,
            "dobr" => Token::Dobr,
            "doco" => Token::Doco,
            "dore" => Token::Dore,
            "doremi" => Token::Doremi,
            "elif" => Token::Condition,
            "else" => Token::Condition,
            "while" => Token::Condition,
            "switch" => Token::Condition,
            "extend" => Token::Extend,
            "fn" => Token::Function,
            "until" => Token::Until,
            "for" => Token::For,
            "foreach" => Token::For,
            "get" => Token::Get,
            "glob" => Token::Global,
            "if" => Token::Condition,
            "inc" => Token::Include,
            "int" => Token::Type,
            "let" => Token::Let,
            "private" => Token::Private,
            "protected" => Token::Protected,
            "pub" => Token::Public,
            "return" => Token::Return,
            "str" => Token::Type,
            "string" => Token::Type,
            "struct" => Token::Struct,
            "use" => Token::Use,
            "true" => Token::True,
            "false" => Token::False,
            _ => Token::Id,
        }
    }

    pub fn is_base(self: &Token) -> bool {
        match self {
            Token::Class => true,
            Token::EOF => true,
            Token::Function => true,
            Token::Get => true,
            Token::Global => true,
            Token::Include => true,
            Token::MacroDefinition => true,
            Token::NewLine => true,
            Token::SemiColon => true,
            Token::Struct => true,
            Token::Use => true,
            Token::Compiler => true,
            _ => false,
        }
    }

    pub fn is_do(self: &Token) -> bool {
        match self {
            Token::Do => true,
            Token::Dobr => true,
            Token::Doco => true,
            Token::Dore => true,
            Token::Doremi => true,
            _ => false
        }
    }
}
